# Generated by Django 3.0.6 on 2020-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_expense', models.CharField(max_length=200)),
                ('type_of_expense', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
